GET http://localhost:3000/companies 

###
POST http://localhost:3000/companies HTTP/1.1
content-type: application/json

{
    "nm_company": "Company B",
    "lg_logo": "log2",
    "nr_phone": "1234",
    "pw_company": "pas",
    "ds_email": "email@e",
    "ds_endereco": "1234"
}
